/*#include <stdio.h>
#include <stdlib.h>
#include "latex2md.tab.h"  // Generated from bison
#include "ast.h"

extern int yyparse();          // The parser function
extern FILE *yyin;             // The input file for the lexer
extern ASTNode *root;          // Root of the AST generated by the parser

int main(int argc, char **argv) {
    if (argc != 3) {
        fprintf(stderr, "Usage: %s <input.tex> <output.md>\n", argv[0]);
        return EXIT_FAILURE;
    }

    // Open the input file
    yyin = fopen(argv[1], "r");
    if (!yyin) {
        perror("Error opening input file");
        return EXIT_FAILURE;
    }

    // Parse the LaTeX file
    if (yyparse() != 0) {
        fprintf(stderr, "Error parsing file\n");
        fclose(yyin);
        return EXIT_FAILURE;
    }

    // Close the input file
    fclose(yyin);

    // Open the output file
    FILE *output = fopen(argv[2], "w");
    if (!output) {
        perror("Error opening output file");
        return EXIT_FAILURE;
    }

    // Convert the AST to Markdown
    to_markdown(root, output);

    // Close the output file
    fclose(output);

    // Free the AST
    free_ast(root);

    return EXIT_SUCCESS;
}
*/